version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1

jobs:
  build_and_push_images_amd64:
    machine:
      image: ubuntu-2404:2024.05.1
      docker_layer_caching: true
    resource_class: medium

    steps:
      - checkout

      - aws-cli/install

      - run:
          name: Authenticate Docker with AWS ECR
          command: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l0d9d4c1

      - run:
          name: Build `telegram` service Docker image for amd64
          working_directory: telegram
          command: |
            docker build -t public.ecr.aws/l0d9d4c1/go-around/telegram:$CIRCLE_SHA1-amd64 -f Dockerfile .
            docker push public.ecr.aws/l0d9d4c1/go-around/telegram:$CIRCLE_SHA1-amd64

  build_and_push_images_arm64:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: arm.medium

    steps:
      - checkout

      - aws-cli/install

      - run:
          name: Authenticate Docker with AWS ECR
          command: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l0d9d4c1

      - run:
          name: Build `telegram-app` service Docker image for arm64
          working_directory: telegram
          command: |
            docker build -t public.ecr.aws/l0d9d4c1/go-around/telegram:$CIRCLE_SHA1-arm64 -f Dockerfile .
            docker push public.ecr.aws/l0d9d4c1/go-around/telegram:$CIRCLE_SHA1-arm64

  create-manifest:
    machine:
      image: ubuntu-2204:current
    steps:
      - aws-cli/install

      - run:
          name: Authenticate Docker with AWS ECR
          command: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l0d9d4c1

      - run:
          name: Create manifest for `telegram-app` service
          command: |
            docker manifest create public.ecr.aws/l0d9d4c1/go-around/telegram:latest public.ecr.aws/l0d9d4c1/go-around/telegram:$CIRCLE_SHA1-arm64 public.ecr.aws/l0d9d4c1/go-around/telegram:$CIRCLE_SHA1-amd64
            docker manifest push public.ecr.aws/l0d9d4c1/go-around/telegram:latest

workflows:
  build:
    jobs:
      - build_and_push_images_amd64:
          filters:
            branches:
              only:
                - main

      - build_and_push_images_arm64:
          filters:
            branches:
              only:
                - main

      - create-manifest:
          requires:
            - build_and_push_images_amd64
            - build_and_push_images_arm64
          filters:
            branches:
              only:
                - main
