namespace GooglePlaces.Models
{
  public static class GooglePlacesTypes
  {
    public static readonly string[] Automotive = [
      "car_dealer",
      "car_rental",
      "car_repair",
      "car_wash",
      "electric_vehicle_charging_station",
      "gas_station",
      "motorcycle_dealer",
      "parking",
      "rest_stop"
    ];

    public static readonly string[] Business = [
      "corporate_office",
      "farm",
      "ranch",
    ];

    public static readonly string[] Culture = [
      "art_gallery",
      "art_studio",
      "auditorium",
      "cultural_landmark",
      "historical_place",
      "monument",
      "museum",
      "performing_arts_theater",
      "sculpture",
    ];

    public static readonly string[] Education = [
      "library",
      "preschool",
      "primary_school",
      "school",
      "secondary_school",
      "university",
    ];

    public static readonly string[] EntertainmentAndRecreation = [
      "adventure_sports_center",
      "amphitheatre",
      "amusement_center",
      "amusement_park",
      "aquarium",
      "banquet_hall",
      "barbecue_area",
      "botanical_garden",
      "bowling_alley",
      "casino",
      "childrens_camp",
      "comedy_club",
      "community_center",
      "convention_center",
      "cultural_center",
      "cycling_park",
      "dance_hall",
      "dog_park",
      "event_venue",
      "ferris_wheel",
      "garden",
      "hiking_area",
      "historical_landmark",
      "internet_cafe",
      "karaoke",
      "marina",
      "movie_rental",
      "movie_theater",
      "national_park",
      "night_club",
      "observation_deck",
      "off_roading_area",
      "opera_house",
      "park",
      "philharmonic_hall",
      "picnic_ground",
      "planetarium",
      "plaza",
      "roller_coaster",
      "skateboard_park",
      "state_park",
      "tourist_attraction",
      "video_arcade",
      "visitor_center",
      "water_park",
      "wedding_venue",
      "wildlife_park",
      "wildlife_refuge",
      "zoo",
    ];

    public static readonly string[] Facilities = [
      "public_bath",
      "public_bathroom",
      "stable",
    ];

    public static readonly string[] Finance = [
      "accounting",
      "atm",
      "bank",
    ];

    public static readonly string[] FoodAndDrink = [
      "acai_shop",
      "afghani_restaurant",
      "african_restaurant",
      "american_restaurant",
      "asian_restaurant",
      "bagel_shop",
      "bakery",
      "bar",
      "bar_and_grill",
      "barbecue_restaurant",
      "brazilian_restaurant",
      "breakfast_restaurant",
      "brunch_restaurant",
      "buffet_restaurant",
      "cafe",
      "cafeteria",
      "candy_store",
      "cat_cafe",
      "chinese_restaurant",
      "chocolate_factory",
      "chocolate_shop",
      "coffee_shop",
      "confectionery",
      "deli",
      "dessert_restaurant",
      "dessert_shop",
      "diner",
      "dog_cafe",
      "donut_shop",
      "fast_food_restaurant",
      "fine_dining_restaurant",
      "food_court",
      "french_restaurant",
      "greek_restaurant",
      "hamburger_restaurant",
      "ice_cream_shop",
      "indian_restaurant",
      "indonesian_restaurant",
      "italian_restaurant",
      "japanese_restaurant",
      "juice_shop",
      "korean_restaurant",
      "lebanese_restaurant",
      "meal_delivery",
      "meal_takeaway",
      "mediterranean_restaurant",
      "mexican_restaurant",
      "middle_eastern_restaurant",
      "pizza_restaurant",
      "pub",
      "ramen_restaurant",
      "restaurant",
      "sandwich_shop",
      "seafood_restaurant",
      "spanish_restaurant",
      "steak_house",
      "sushi_restaurant",
      "tea_house",
      "thai_restaurant",
      "turkish_restaurant",
      "vegan_restaurant",
      "vegetarian_restaurant",
      "vietnamese_restaurant",
      "wine_bar",
    ];

    public static readonly string[] GeographicalAreas = [
      "administrative_area_level_1",
      "administrative_area_level_2",
      "country",
      "locality",
      "postal_code",
      "school_district",
    ];

    public static readonly string[] Government = [
      "city_hall",
      "courthouse",
      "embassy",
      "fire_station",
      "government_office",
      "local_government_office",
      "neighborhood_police_station",
      "police",
      "post_office",
    ];

    public static readonly string[] HealthAndWellness = [
      "chiropractor",
      "dental_clinic",
      "dentist",
      "doctor",
      "drugstore",
      "hospital",
      "massage",
      "medical_lab",
      "pharmacy",
      "physiotherapist",
      "sauna",
      "skin_care_clinic",
      "spa",
      "tanning_studio",
      "wellness_center",
      "yoga_studio",
    ];

    public static readonly string[] Housing = [
      "apartment_building",
      "apartment_complex",
      "condominium_complex",
      "housing_complex",
    ];

    public static readonly string[] Lodging = [
      "bed_and_breakfast",
      "budget_japanese_inn",
      "campground",
      "camping_cabin",
      "cottage",
      "extended_stay_hotel",
      "guest_house hostel",
      "hotel",
      "inn",
      "japanese_inn",
      "lodging",
      "mobile_home_park",
      "motel",
      "private_guest_room",
      "resort_hotel",
      "rv_park",
    ];

    public static readonly string[] NaturalFeatures = [
      "beach",
    ];

    public static readonly string[] PlacesOfWorship = [
      "church",
      "hindu_temple",
      "mosque",
      "synagogue",
    ];

    public static readonly string[] Services = [
      "astrologer",
      "barber_shop",
      "beautician",
      "beauty_salon",
      "body_art_service",
      "catering_service",
      "cemetery",
      "child_care_agency",
      "consultant",
      "courier_service",
      "electrician",
      "florist",
      "food_delivery",
      "foot_care",
      "funeral_home",
      "hair_care",
      "hair_salon",
      "lawyer",
      "locksmith",
      "makeup_artist",
      "moving_company",
      "nail_salon",
      "painter",
      "plumber",
      "psychic",
      "real_estate_agency",
      "roofing_contractor",
      "storage",
      "summer_camp_organizer",
      "tailor",
      "telecommunications_service_provider",
      "tour_agency",
      "tourist_information_center",
      "travel_agency",
      "veterinary_care",
    ];

    public static readonly string[] Shopping = [
      "asian_grocery_store",
      "auto_parts_store",
      "bicycle_store",
      "book_store",
      "butcher_shop",
      "cell_phone_store",
      "clothing_store",
      "convenience_store",
      "department_store",
      "discount_store",
      "electronics_store",
      "food_store",
      "furniture_store",
      "gift_shop",
      "grocery_store",
      "hardware_store",
      "home_goods_store",
      "home_improvement_store",
      "jewelry_store",
      "liquor_store",
      "market",
      "pet_store",
      "shoe_store",
      "shopping_mall",
      "sporting_goods_store",
      "store",
      "supermarket",
      "warehouse_store",
      "wholesaler",
    ];

    public static readonly string[] Sports = [
      "arena",
      "athletic_field",
      "fishing_charter",
      "fishing_pond",
      "fitness_center",
      "golf_course",
      "gym",
      "ice_skating_rink",
      "playground",
      "ski_resort",
      "sports_activity_location",
      "sports_club",
      "sports_coaching",
      "sports_complex",
      "stadium",
      "swimming_pool",
    ];

    public static readonly string[] Transportation = [
      "airport",
      "airstrip",
      "bus_station",
      "bus_stop",
      "ferry_terminal",
      "heliport",
      "international_airport",
      "light_rail_station",
      "park_and_ride",
      "subway_station",
      "taxi_stand",
      "train_station",
      "transit_depot",
      "transit_station",
      "truck_stop",
    ];

    public static readonly string[] AdditionalPlaceTypeValues = [
      "administrative_area_level_3",
      "administrative_area_level_4",
      "administrative_area_level_5",
      "administrative_area_level_6",
      "administrative_area_level_7",
      "archipelago",
      "colloquial_area",
      "continent",
      "establishment",
      "finance",
      "floor",
      "food",
      "general_contractor",
      "geocode",
      "health",
      "intersection",
      "landmark",
      "natural_feature",
      "neighborhood",
      "place_of_worship",
      "plus_code",
      "point_of_interest",
      "political",
      "post_box",
      "postal_code_prefix",
      "postal_code_suffix",
      "postal_town",
      "premise",
      "room",
      "route",
      "street_address",
      "street_number",
      "sublocality",
      "sublocality_level_1",
      "sublocality_level_2",
      "sublocality_level_3",
      "sublocality_level_4",
      "sublocality_level_5",
      "subpremise",
      "town_square",
    ];

    public static readonly Dictionary<string, string[]> Categories = new Dictionary<string, string[]>()
    {
      {"automotive", Automotive},
      {"business", Business},
      {"culture", Culture},
      {"education", Education},
      {"entertainmentAndRecreation", EntertainmentAndRecreation},
      {"facilities", Facilities},
      {"finance", Finance},
      {"foodAndDrink", FoodAndDrink},
      {"geographicalAreas", GeographicalAreas},
      {"government", Government},
      {"healthAndWellness", HealthAndWellness},
      {"housing", Housing},
      {"lodging", Lodging},
      {"naturalFeatures", NaturalFeatures},
      {"placesOfWorship", PlacesOfWorship},
      {"services", Services},
      {"shopping", Shopping},
      {"sports", Sports},
      {"transportation", Transportation},
      {"additionalPlaceTypeValues", AdditionalPlaceTypeValues},
    };
  }
}